### ISSUE TITLE
Add Typescript support for NextJS app

### ISSUE THREAD

**Issue by catalinpopusoi** [iampava/frontend.ro#10]
NextJS already supports Typescript out of the box. It just needs to be configured based on the docs below:
https://nextjs.org/docs/basic-features/typescript

This configuration will follow in the next PR.

**Comment by catalinpopusoi** [comment]
A PR is now raised. You can check it out here: #11

**Comment by iampava** [comment]
Merged PR. Closing this issue. Thanks ^^^
