### ISSUE TITLE
Sign in/Register with own email & GitHub

### ISSUE THREAD

**Issue by iampava** [iampava/frontend.ro#13]
Viewing the tutorials & exercises will be free, However, submitting an exercise will require an account.

We'll offer 2 options:
* register with own email & password
* register with GitHub (since this is a developer oriented website, I think a lot of people have a GitHub account)

We'll have two kind of routes:
* `public` - you don't need to be logged in to access them (ex: tutorials page)
* `private` - you need to be logged in (ex: feedback routes)

We need to offer a seamless experience, so if you access a `private` route while you're logged out, let's temporarily redirect to a login page, and after login redirect back to the intended one.

We need to set up the REST API in Node.js and the client side verifications and routing. 

I propose we do the login via JWT. 

Also, a lot of this code is already implemented in https://DevDrive.io - another app I built, so to move fast I propose we re-use as much of the code as we can.

**Comment by iampava** [comment]
Copy-pasted here - https://github.com/iampava/frontend.ro/tree/master/frontend-ssr/components/login - some FrontEnd code regarding login (used in https://DevDrive.io).

The focus was on having a functional version until university starts, so I definitely cut some corners. If you think of ways to improve the code, please don't hesitate.

I'll just quickly explain the idea behind 2 files:

1. **Form.jsx** -> this is a wrapper around a usual `<form>` element with some extra functionality and validation. Implemented it so we don't have duplicate code
2. **Http.service.js** -> this is a wrapper around the native `fetch` API to allow easy communication with the REST API. You might wonder why I didn't use [axios](https://www.npmjs.com/package/axios). Well, it's kinda big at 13KB - https://bundlephobia.com/result?p=axios@0.19.2 - for what we need so to focus on performance i decided to make this wrapper specifically for DevDrive.

**Comment by SirCQQ** [comment]
Starting `user` routes for : Login, Register, User-info + Login/Register Pages

**Comment by andyrkn** [comment]
will the node.js source be public on git or is it not started yet?

**Comment by iampava** [comment]
Everything will be public with some exceptions to guarantee security. The Node.js backend is not started yet, sooooo if you wanna help it would be much appreciated. :D

**Comment by iampava** [comment]
Closing this issue. Register/login with own email has been implemented. Will  open a new issue for github-based authentication
