### ISSUE TITLE
Checkpoints during the tutorial

### ISSUE THREAD

**Issue by silidragos** [iampava/frontend.ro#24]
During longer tutorials, it can be motivating to have a checkpoint list that autocompletes while scrolling. 
![image](https://user-images.githubusercontent.com/7973330/92371862-d8578900-f104-11ea-980f-00d76233ea93.png)

**Comment by andreeatoma** [comment]
I will build this awesome component! 👍

**Comment by iampava** [comment]
This component has already been built. Closing this issue.
